### ISSUE TITLE
List of supported languages

### ISSUE THREAD

**Issue by infojunkie** [bsolomon1124/pycld3#12]
Is there a way to get the list of supported languages in the `cld3` model?

**Comment by bsolomon1124** [comment]
I don't actually see it documented in the CLD3 README, but browsing through the [CLD3 source code](https://github.com/google/cld3/tree/master/src), I do see a set of [formally tested languages](https://github.com/google/cld3/blob/06f695f1c8ee530104416aab5dcf2d6a1414a56a/src/nnet_lang_id_test.cc#L36).

**Comment by infojunkie** [comment]
Thanks for looking! Not sure if you'd be interested to consider this as a feature request (which would probably need an upstream feature request as well) - so feel free to close this. I can manually copy the list for now :pray:

**Comment by infojunkie** [comment]
One detail, though: I get some results as `hi-Latn` which are not showing in these tests, as per https://github.com/bsolomon1124/pycld3/blob/0c59028dd5d8affd5a28e3c5c66e6fda98534407/src/task_context_params.cc#L43-L53. So I guess the tests are not covering the totality of the model training.

**Comment by bsolomon1124** [comment]
You're right, it does look like that list is more extensive.

In terms of documentation, I would be more comfortable linking to the CLD3 list in the PyCLD3 docs rather than maintaining our own static copy.  I'll leave this issue open and can work on adding that in.

**Comment by viv1729** [comment]
@bsolomon1124 I can see examples for language code [here](https://github.com/bsolomon1124/pycld3/blob/master/src/nnet_lang_id_test_data.cc). But is there any mapping; how would I know which code maps to which languages apart from few obvious ones?

**Comment by bsolomon1124** [comment]
@viv1729 unfortunately you are asking the wrong guy 😞 . And the cld3 maintainers don't exactly seem responsive.

**Comment by loretoparisi** [comment]
@infojunkie good catch-up! I'm using CLD-2 and I have noticed that for `zh` here they have `"zh-Latn"` that guess is romanized chinese (transcription from the source script)? Also they don't seem to support `zh-hant` (tradizional chinese) like the good old CLD-2 did. I'm not sure of, btw because it seems there is no official list...

**Comment by bact** [comment]
This PR at Google CLD3 https://github.com/google/cld3/pull/38 now listed all the supported languages in its README.md. pycld3 can just point to that list.
