### ISSUE TITLE
google/protobuf/port_def.inc not found

### ISSUE THREAD

**Issue by alphabetagamer** [bsolomon1124/pycld3#16]
I downloaded ms c++ 14.0  , downloaded protobuf binary and added it to my path , downloaded protobuf for python via pip and still receive this error while executing pip install pycld3 . Could someone explain to me why is it not working . I have no experience with protobuf so I am unable to understand the errors

**Comment by bsolomon1124** [comment]
Closing as duplicate of https://github.com/bsolomon1124/pycld3/issues/17 since that issue contains additional info.
