### ISSUE TITLE
cld3 predict bad case: "hello world" result is 'ky'

### ISSUE THREAD

**Issue by EchoLOLROF** [bsolomon1124/pycld3#20]
>>> import cld3
>>> cld3.get_language('hello world')
LanguagePrediction(language='ky', probability=0.7191877961158752, is_reliable=True, proportion=1.0)

**Comment by bsolomon1124** [comment]
As documented in the [README](https://github.com/bsolomon1124/pycld3#cld3-incorrectly-detects-my-input--how-can-i-fix-this), pycld3 is a Python wrapper for cld3. It does not do any novel language detection of its own. It may be unreliable for short inputs such as this. Please open any detection quality issues with https://github.com/google/cld3/.
