### ISSUE TITLE
cld3/pycld3.cpp missing from source list.

### ISSUE THREAD

**Issue by Ursidaeic** [bsolomon1124/pycld3#24]
As detailed in [this](https://stackoverflow.com/questions/66386066/c1xx-fatal-error-c1083-cannot-open-source-file-cld3-pycld3-cpp-no-such-fi/66386605#66386605) post, when trying to install pycld3 on my windows 10 machine it throws up the following error: c1xx: fatal error C1083: Cannot open source file: 'cld3/pycld3.cpp': No such file or directory

**Comment by phdru** [comment]
`cld3/pycld3.cpp` must be included in sdist regardless of presence of Cython at the sdist generation time. If the user lacks Cython `cld3/pycld3.cpp` will be used instead.

**Comment by bsolomon1124** [comment]
Thanks for reporting this and leading me to the StackOverflow question. I'll address this bug today.

**Comment by bsolomon1124** [comment]
This issue should be resolved in pycld3 [release 0.22](https://pypi.org/project/pycld3/).

```bash
python3 -m pip install -U pycld3
```

As @phdru points out, this was an error with the distribution upload in 0.21 that neglected to include the intermediate .cpp file. Inclusion of that file in the sdist should not be dependent on the build-time logic of whether a user has or wants to use Cython.

Note that in the 0.22 release, the installation will respect the environment variable `USE_CYTHON=1`. You must have an existing install of Cython to use this flag. It will force re-compilation from the source .pyx file. This follows the behavior recommended at [Distributing Cython Modules](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules). 

0.22 also drops support for end-of-life Python 3.5 and no longer passes the unsupported -std=c++11 on Windows MSVC.

Detail: [full changelog from 0.21 to 0.22](https://github.com/bsolomon1124/pycld3/compare/4fb7f92d26e5c8ee3ded03cabb71e4845af2b75c...af6187d4020eafbe3f8517fa144072a8aa1d9bbc).

Please let me know if any issues and I will re-open.
