### ISSUE TITLE
Linux wheels

### ISSUE THREAD

**Issue by alexcombessie** [bsolomon1124/pycld3#8]
Hi there,

Very interesting work. Sadly, I can't use it in my context as I am building an app which needs to be compatible with all kinds of Linux operating systems...

Do you have any short term plans to provide wheels for a variety of Python versions and many OS?

Cheers,

Alex

**Comment by bsolomon1124** [comment]
Hi @alexcombessie , I would like to build `manylinux` wheels for this project but I can't guarantee I'll get to it very soon.  Wish I had more time to devote to this project but have been spread thin lately.

**Comment by bsolomon1124** [comment]
Leaving a note here for myself:

> https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh

**Comment by alexcombessie** [comment]
Thanks!

**Comment by bsolomon1124** [comment]
@alexcombessie just wanted to let you know I'm working on building wheels for [MacOS](https://github.com/bsolomon1124/pycld3/actions/runs/73662976) and manylinux (Python 3.5 thru 3.8) and optimistically should have something by end of week.

**Comment by alexcombessie** [comment]
@bsolomon1124 that would be incredible!!!

**Comment by bsolomon1124** [comment]
Ok @alexcombessie , I've uploaded some wheels to Test PyPI.  Working for me on Ubuntu & Alpine, but could you be kind enough to try on your end?  Should be as simple as:

```shell
$ pip install --index-url https://test.pypi.org/simple/ pycld3
$ python -c 'import cld3; print(cld3.get_language("影響包含對氣候的變化以及自然資源的枯竭程度"))'
```

**Comment by alexcombessie** [comment]
Thanks, I confirm it works perfectly on RHEL/CentOS 7 for python 3.5, 3.6,
3.7 and 3.8

Looks like it's good to go on the real PyPi!

**Comment by bsolomon1124** [comment]
[Wheels](https://pypi.org/project/pycld3/#files) are now uploaded to production PyPI.

```
python -m pip install -U pip pycld3
```

Please let me know if anything here is unresolved and I can re-open.  Thanks!
